server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_receivable
    username: s2it_lgoncalo
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
